"""Add status column to Interface

Revision ID: 4e607e7ce9e0
Revises: 1ccba2c6b829
Create Date: 2025-08-08 17:41:47.640173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e607e7ce9e0'
down_revision = '1ccba2c6b829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interface', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interface', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
